name: bos deploy
description: Deploys BOS components to a configured account
runs:
  using: docker
  image: ubuntu-latest
inputs:
  cli-version:
    description: "Version of near-social CLI to use for deploy"
    required: true
    default: "0.2.5"
  deploy-account-address:
    description: "Account under which component code should be deployed"
    required: true
  signer-account-address:
    description: "Account which will be used for signing deploy transaction, frequently the same as deploy-account-address"
    required: true
  signer-public-key:
    description: "Public key in TODO format for signing transaction"
    required: true
  signer-private-key:
    description: "Private key in TODO format for signing transaction. DO NOT hardcode this value, it should be stored as a repository secret"
    required: true
branding:
  icon: "link"
